#[derive(Debug, PartialEq, Eq, Clone)]
pub enum Peer {
    Hover,
    Focus,
    FocusWithin,
    FocusVisible,
    Active,
    Visited,
    Target,
    First,
    Last,
    Only,
    Odd,
    Even,
    FirstOfType,
    LastOfType,
    OnlyOfType,
    Empty,
    Disabled,
    Enabled,
    Checked,
    Indeterminate,
    Default,
    Required,
    Valid,
    Invalid,
    InRange,
    OutOfRange,
    PlaceholderShown,
    Autofill,
    ReadOnly,
    Open,
}

impl Peer {
    pub fn new(value: &str) -> Option<Self> {
        let g = match value {
            "peer-hover" => Peer::Hover,
            "peer-focus" => Peer::Focus,
            "peer-focus-within" => Peer::FocusWithin,
            "peer-focus-visible" => Peer::FocusVisible,
            "peer-active" => Peer::Active,
            "peer-visited" => Peer::Visited,
            "peer-target" => Peer::Target,
            "peer-first-child" => Peer::First,
            "peer-last-child" => Peer::Last,
            "peer-only-child" => Peer::Only,
            "peer-nth-child(odd)" => Peer::Odd,
            "peer-nth-child(even)" => Peer::Even,
            "peer-first-of-type" => Peer::FirstOfType,
            "peer-last-of-type" => Peer::LastOfType,
            "peer-only-of-type" => Peer::OnlyOfType,
            "peer-empty" => Peer::Empty,
            "peer-disabled" => Peer::Disabled,
            "peer-enabled" => Peer::Enabled,
            "peer-checked" => Peer::Checked,
            "peer-indeterminate" => Peer::Indeterminate,
            "peer-default" => Peer::Default,
            "peer-required" => Peer::Required,
            "peer-valid" => Peer::Valid,
            "peer-invalid" => Peer::Invalid,
            "peer-in-range" => Peer::InRange,
            "peer-out-of-range" => Peer::OutOfRange,
            "peer-placeholder-shown" => Peer::PlaceholderShown,
            "peer-autofill" => Peer::Autofill,
            "peer-readonly" => Peer::ReadOnly,
            "peer-open" => Peer::Open,
            _ => return None,
        };

        Some(g)
    }

    pub fn to_static_str(&self) -> &'static str {
        match self {
            Peer::Hover => "peer:hover ~ .",
            Peer::Focus => "peer:focus ~ .",
            Peer::FocusWithin => "peer:focus-within ~ .",
            Peer::FocusVisible => "peer:focus-visible ~ .",
            Peer::Active => "peer:active ~ .",
            Peer::Visited => "peer:visited ~ .",
            Peer::Target => "peer:target ~ .",
            Peer::First => "peer:first-child ~ .",
            Peer::Last => "peer:last-child ~ .",
            Peer::Only => "peer:only-child ~ .",
            Peer::Odd => "peer:nth-child(odd) ~ .",
            Peer::Even => "peer:nth-child(even) ~ .",
            Peer::FirstOfType => "peer:first-of-type ~ .",
            Peer::LastOfType => "peer:last-of-type ~ .",
            Peer::OnlyOfType => "peer:only-of-type ~ .",
            Peer::Empty => "peer:empty ~ .",
            Peer::Disabled => "peer:disabled ~ .",
            Peer::Enabled => "peer:enabled ~ .",
            Peer::Checked => "peer:checked ~ .",
            Peer::Indeterminate => "peer:indeterminate ~ .",
            Peer::Default => "peer:default ~ .",
            Peer::Required => "peer:required ~ .",
            Peer::Valid => "peer:valid ~ .",
            Peer::Invalid => "peer:invalid ~ .",
            Peer::InRange => "peer:in-range ~ .",
            Peer::OutOfRange => "peer:out-of-range ~ .",
            Peer::PlaceholderShown => "peer:placeholder-shown ~ .",
            Peer::Autofill => "peer:autofill ~ .",
            Peer::ReadOnly => "peer:readonly ~ .",
            Peer::Open => "peer:open ~ .",
        }
    }
}
