#[derive(Debug, PartialEq, Eq)]
pub enum PseudoClass {
    Hover,
    Focus,
    FocusWithin,
    FocusVisible,
    Active,
    Visited,
    Target,
    First,
    Last,
    Only,
    Odd,
    Even,
    FirstOfType,
    LastOfType,
    OnlyOfType,
    Empty,
    Disabled,
    Enabled,
    Checked,
    Indeterminate,
    Default,
    Required,
    Valid,
    Invalid,
    InRange,
    OutOfRange,
    PlaceholderShown,
    Autofill,
    ReadOnly,
    Open,
}

impl PseudoClass {
    pub fn as_str(&self) -> &'static str {
        match self {
            PseudoClass::Hover => "hover",
            PseudoClass::Focus => "focus",
            PseudoClass::FocusWithin => "focus-within",
            PseudoClass::FocusVisible => "focus-visible",
            PseudoClass::Active => "active",
            PseudoClass::Visited => "visited",
            PseudoClass::Target => "target",
            PseudoClass::First => "first-child",
            PseudoClass::Last => "last-child",
            PseudoClass::Only => "only-child",
            PseudoClass::Odd => "nth-child(odd)",
            PseudoClass::Even => "nth-child(even)",
            PseudoClass::FirstOfType => "first-of-type",
            PseudoClass::LastOfType => "last-of-type",
            PseudoClass::OnlyOfType => "only-of-type",
            PseudoClass::Empty => "empty",
            PseudoClass::Disabled => "disabled",
            PseudoClass::Enabled => "enabled",
            PseudoClass::Checked => "checked",
            PseudoClass::Indeterminate => "indeterminate",
            PseudoClass::Default => "default",
            PseudoClass::Required => "required",
            PseudoClass::Valid => "valid",
            PseudoClass::Invalid => "invalid",
            PseudoClass::InRange => "in-range",
            PseudoClass::OutOfRange => "out-of-range",
            PseudoClass::PlaceholderShown => "placeholder-shown",
            PseudoClass::Autofill => "autofill",
            PseudoClass::ReadOnly => "readonly",
            PseudoClass::Open => "open",
        }
    }

    pub fn parse_from_str(str: &str) -> Option<PseudoClass> {
        match str {
            "hover" => Some(PseudoClass::Hover),
            "focus" => Some(PseudoClass::Focus),
            "focus-within" => Some(PseudoClass::FocusWithin),
            "focus-visible" => Some(PseudoClass::FocusVisible),
            "active" => Some(PseudoClass::Active),
            "visited" => Some(PseudoClass::Visited),
            "target" => Some(PseudoClass::Target),
            "first-child" => Some(PseudoClass::First),
            "last-child" => Some(PseudoClass::Last),
            "only-child" => Some(PseudoClass::Only),
            "nth-child(odd)" => Some(PseudoClass::Odd),
            "nth-child(even)" => Some(PseudoClass::Even),
            "first-of-type" => Some(PseudoClass::FirstOfType),
            "last-of-type" => Some(PseudoClass::LastOfType),
            "only-of-type" => Some(PseudoClass::OnlyOfType),
            "empty" => Some(PseudoClass::Empty),
            "disabled" => Some(PseudoClass::Disabled),
            "enabled" => Some(PseudoClass::Enabled),
            "checked" => Some(PseudoClass::Checked),
            "indeterminate" => Some(PseudoClass::Indeterminate),
            "default" => Some(PseudoClass::Default),
            "required" => Some(PseudoClass::Required),
            "valid" => Some(PseudoClass::Valid),
            "invalid" => Some(PseudoClass::Invalid),
            "in-range" => Some(PseudoClass::InRange),
            "out-of-range" => Some(PseudoClass::OutOfRange),
            "placeholder-shown" => Some(PseudoClass::PlaceholderShown),
            "autofill" => Some(PseudoClass::Autofill),
            "readonly" => Some(PseudoClass::ReadOnly),
            "open" => Some(PseudoClass::Open),
            _ => None,
        }
    }
}
